DATA:
  IMAGE_SIZE: 224
MODEL:
  CHECKPOINT: null # null == None, 불러올 모델
  N_CLASSES: 2 # class 개수
TRAIN:
  LR: 0.001
  BATCH_SIZE: 2
  SEED: 2022
  EPOCHS: 100
  EARLYSTOP_PATIENT: 10
  DEVICE: cpu
  MODEL_SAVE_PATH: './ckpt/template/best.pth'
  LOGGING_SEP: '|'
  LOGGING_SAVE_PATH: './log.txt'
TEST: